---
- name: Make sure ntpsec is installed
  ansible.builtin.package:
    name: ntpsec
    state: present
  tags: ntp

- name: Make sure ntpsec is running and enabled
  ansible.builtin.service:
    name: ntpsec
    state: started
    enabled: true
  tags: ntp

# Translate the ansible provided architecture name to debian style architecture names
- name: Set DPKG architecture
  ansible.builtin.set_fact:
    dpkg_arch: '{{ {"x86_64": "amd64", "aarch64": "arm64"}[ansible_facts["architecture"]] | default("") }}'
  tags: always

- name: Update the /etc/hosts file with node name
  ansible.builtin.lineinfile:
    dest: "/etc/hosts"
    regexp: '.*{{ inventory_hostname }}$'
    line: "127.0.0.1 {{ inventory_hostname }}"
    state: present
  tags: etchostsupdate
