apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: entertainment
resources:
- namespace.yaml
- heimdall.yaml
- jellyfin.yaml
- prowlarr.yaml
- sonarr.yaml
- radarr.yaml
- jackett.yaml
- ombi.yaml
- transmission.yaml
- metube.yaml

generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: secrets
    secretFrom:
    - metadata:
        name: wireguard
        annotations:
          kustomize.config.k8s.io/needs-hash: "true"
      files:
      - wg0.conf=./wireguard.enc.ini
