---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ombi
  labels:
    app: ombi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ombi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ombi
    spec:
      containers:
      - image: lscr.io/linuxserver/ombi:latest
        imagePullPolicy: Always
        name: ombi
        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "Asia/Karachi"
        volumeMounts:
        - mountPath: /config
          name: config
        ports:
        - containerPort: 3579
        livenessProbe:
          tcpSocket:
            port: 3579
          initialDelaySeconds: 600
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 3579
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"
          limits:
            memory: "512Mi"
      volumes:
        - name: config
          hostPath:
            path: /home/entertainment/ombi
            type: Directory
      nodeSelector:
        disk-type: media
---
apiVersion: v1
kind: Service
metadata:
  name: ombi
  labels:
    app: ombi
spec:
  ports:
  - port: 3579
    protocol: TCP
    targetPort: 3579
  selector:
    app: ombi
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ombi
  labels:
    app: ombi
  annotations:
    kubernetes.io/ingress.class: "nginx"
    gethomepage.dev/description: Media Requests
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Entertainment
    gethomepage.dev/icon: ombi.png
    gethomepage.dev/name: Ombi
    gethomepage.dev/weight: "91"
    gethomepage.dev/widget.type: ombi
    gethomepage.dev/widget.url: http://ombi.entertainment.svc:3579
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_OMBI_KEY}}"
spec:
  tls:
  - hosts:
    - ombi.home.com
  rules:
  - host: ombi.home.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ombi
            port:
              number: 3579
