---
apiVersion: v1
kind: Service
metadata:
  name: legacy-proxy
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: legacy-proxy
subsets:
  - addresses:
      - ip: y.y.y.y
    ports:
      - port: 80
        name: http
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: legacy-proxy
  labels:
    app: legacy-proxy
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - '*.home.com'
  rules:
  - host: '*.home.com'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: legacy-proxy
            port:
              number: 80
