---
apiVersion: v1
kind: Service
metadata:
  name: byedpi
  labels:
    app: byedpi
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: y.y.y.y
  ports:
  - name: socks
    port: 1080
    protocol: TCP
    targetPort: socks
  selector:
    app: byedpi
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: byedpi
  name: byedpi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: byedpi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: byedpi
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - y.y.y.y
      containers:
      - image: tazihad/byedpi:v0.16
        name: byedpi
        args:
        - --ip=0.0.0.0
        - --port=1080
        - --disorder
        - "1"
        - --auto=torst
        - --tlsrec
        - "1+s"
        # - --no-domain
        # - --debug=2
        ports:
        - containerPort: 1080
          name: socks
          protocol: TCP          
        resources:
          requests:
            cpu: 100m
          limits:
            memory: 256Mi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node1
                - node3
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - byedpi
            topologyKey: "kubernetes.io/hostname"
