---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    headerStyle: boxed
    target: _self
    layout:
    - Entertainment:
    - Home Automation:
    - Networking:
    - Utilities:
  docker.yaml: ""
  custom.css: ""
  custom.js: "" 
  bookmarks.yaml: ""
  services.yaml: |
    - Home Automation:
        - Homebridge:
            href: https://homebridge.home.com/
            icon: homebridge.png
            description: HomeKit bridge
            widget:
                type: homebridge
                url: https://homebridge.home.com
                username: {{HOMEPAGE_VAR_HOMEBRIDGE_USERNAME}}
                password: {{HOMEPAGE_VAR_HOMEBRIDGE_PASSWORD}}
    - Networking:
        - PiHole:
            href: https://pdns.home.com/admin/
            icon: pi-hole.png
            description: DNS, DHCP & Ad Blocker
            widget:
                type: pihole
                url: https://pdns.home.com
                key: {{HOMEPAGE_VAR_PIHOLE_KEY}}
        - Unifi:
            href: https://unifi.home.com/
            icon: unifi-controller.png
            description: Network Management Console
    - Utilities:
        - Gitea:
            href: https://git.project.com/
            icon: gitea.png
            description: Git server
        - Monica:
            href: https://monica.home.com
            icon: monica.png
            description: Personal CRM
  widgets.yaml: |
    - unifi_console:
        url: https://unifi.home.com
        username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
        password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: google
        target: _self
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  labels:
    app: homepage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
  labels:
    app: homepage
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
  labels:
    app: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: utilities
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  labels:
    app: homepage
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: homepage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  labels:
    app: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:latest"
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: homepage
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: homepage-config
              mountPath: /app/config
            - name: logs
              mountPath: /app/config/logs
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: logs
          emptyDir:
            {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  labels:
    app: homepage
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-signin: https://iap.home.com/oauth2/start?rd=https://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.utilities.svc.cluster.local/oauth2/auth
    nginx.ingress.kubernetes.io/auth-snippet: |
      # Disable authentication for these endpoints
      if ( $request_uri ~ "/apple-touch-icon.png" ) {
         return 200;
      }
    nginx.ingress.kubernetes.io/auth-cache-key: $cookie__oauth2_proxy
    nginx.ingress.kubernetes.io/auth-cache-duration: 200 202 10m, 401 0m
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  tls:
  - hosts:
    - home.com
  rules:
    - host: "home.com"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 3000
