apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
resources:
- namespace.yaml
- homepage.yaml
- hammond.yaml
- ups.yaml
- pihole.yaml
- tailscale.yaml
- ddclient.yaml
- speedtest.yaml

helmCharts:
- name: oauth2-proxy
  repo: https://oauth2-proxy.github.io/manifests
  releaseName: oauth2-proxy
  version: 7.1.0
  valuesFile: oauth2-proxy.yaml

generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: secret-envs
    secretFrom:
    - metadata:
        name: homepage
        annotations:
          kustomize.config.k8s.io/needs-hash: "true"
      envs:
      - ./homepage.enc.env
    - metadata:
        name: pihole
        annotations:
          kustomize.config.k8s.io/needs-hash: "true"
      envs:
      - ./pihole.enc.env
    - metadata:
        name: tailscale
        annotations:
          kustomize.config.k8s.io/needs-hash: "false"
      envs:
      - ./tailscale.enc.env
    - metadata:
        name: ddclient
        annotations:
          kustomize.config.k8s.io/needs-hash: "true"
      files:
      - ddclient.conf=./ddclient.enc.conf
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: secret-files
    files:
      - ./oauth2-proxy.enc.yaml
