apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
resources:
- namespace.yaml
- homepage.yaml
- ups.yaml
- pihole.yaml
- tailscale.yaml
- ddclient.yaml
- speedtest.yaml
- apcupsd.yaml
- zte-hack.yaml
- lubelogger.yaml
- httpbin.yaml
- backups.yaml
- byedpi.yaml
- actualbudget.yaml

generators:
- |
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: secret-envs
    annotations:
      config.kubernetes.io/function: |
          exec:
            path: ksops
  secretFrom:
  - metadata:
      name: homepage
      annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    envs:
    - ./homepage.enc.env
  - metadata:
      name: pihole
      annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    envs:
    - ./pihole.enc.env
  - metadata:
      name: lubelogger
      annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    envs:
    - ./lubelogger.enc.env
  - metadata:
      name: tailscale
      annotations:
        kustomize.config.k8s.io/needs-hash: "false"
    envs:
    - ./tailscale.enc.env
  - metadata:
      name: zte-hack
      annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    envs:
    - ./zte-hack.enc.env
  - metadata:
      name: ddclient
      annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    files:
    - ddclient.conf=./ddclient.enc.conf
  - metadata:
      name: backups
      annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    files:
    - id_rsa=./backups.enc.pem
