apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
resources:
- namespace.yaml
- homepage.yaml
- hammond.yaml
- ups.yaml
- pihole.yaml
- tailscale.yaml
- ddclient.yaml
- speedtest.yaml
- apcupsd.yaml

helmCharts:
- name: oauth2-proxy
  releaseName: oauth2-proxy
  repo: https://oauth2-proxy.github.io/manifests
  valuesFile: oauth2-proxy.yaml
  version: 7.7.4

generators:
- |
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: secret-envs
    annotations:
      config.kubernetes.io/function: |
          exec:
            path: ksops
  secretFrom:
  - metadata:
      name: homepage
      annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    envs:
    - ./homepage.enc.env
  - metadata:
      name: pihole
      annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    envs:
    - ./pihole.enc.env
  - metadata:
      name: tailscale
      annotations:
        kustomize.config.k8s.io/needs-hash: "false"
    envs:
    - ./tailscale.enc.env
  - metadata:
      name: ddclient
      annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    files:
    - ddclient.conf=./ddclient.enc.conf
- |
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: secret-files
    annotations:
      config.kubernetes.io/function: |
          exec:
            path: ksops
  files:
    - ./oauth2-proxy.enc.yaml
