apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
resources:
- namespace.yaml
- homepage.yaml
- hammond.yaml

helmCharts:
- name: pihole
  repo: https://mojo2600.github.io/pihole-kubernetes/
  releaseName: pihole
  version: 2.23.0
  valuesFile: pihole.yaml


generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: secrets
    secretFrom:
    - metadata:
        name: homepage
        annotations:
          kustomize.config.k8s.io/needs-hash: "true"
      envs:
      - ./homepage.enc.env
