apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
resources:
- namespace.yaml
- code-server.yaml
- homepage.yaml
- ups.yaml
- apcupsd.yaml
- backups.yaml
- oidc-discovery.yaml

generators:
- |
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: secret-envs
    annotations:
      config.kubernetes.io/function: |
          exec:
            path: ksops
  secretFrom:
  - metadata:
      name: homepage
      annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    envs:
    - ./homepage.enc.env
  - metadata:
      name: backups
      annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    files:
    - id_rsa=./backups.enc.pem
