---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lubelogger
  labels:
    app: lubelogger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lubelogger
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lubelogger
    spec:
      containers:
      - image: ghcr.io/hargata/lubelogger:v1.6.8
        imagePullPolicy: IfNotPresent
        name: lubelogger
        env:
        - name: LC_ALL
          value: en_GB.UTF-8
        - name: LANG
          value: en_GB.UTF-8
        envFrom:
        - secretRef:
            name: lubelogger        
        volumeMounts:
        - mountPath: /App/config
          name: config
        - mountPath: /App/data
          name: data
        - mountPath: /App/wwwroot/translations
          name: translations
        - mountPath: /App/wwwroot/documents
          name: documents
        - mountPath: /App/wwwroot/images
          name: images
        - mountPath: /App/wwwroot/temp
          name: temp
        - mountPath: /App/log
          name: log
        - mountPath: /root/.aspnet/DataProtection-Keys
          name: keys
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: http
            path: /manifest.json
        resources:
          requests:
            cpu: "100m"
          limits:
            memory: "256Mi"
      volumes:
        - name: config
          hostPath:
            path: /home/utilities/lubelogger/config
            type: DirectoryOrCreate
        - name: data
          hostPath:
            path: /home/utilities/lubelogger/data
            type: DirectoryOrCreate
        - name: translations
          hostPath:
            path: /home/utilities/lubelogger/translations
            type: DirectoryOrCreate
        - name: documents
          hostPath:
            path: /home/utilities/lubelogger/documents
            type: DirectoryOrCreate
        - name: images
          hostPath:
            path: /home/utilities/lubelogger/images
            type: DirectoryOrCreate
        - name: temp
          hostPath:
            path: /home/utilities/lubelogger/temp
            type: DirectoryOrCreate
        - name: log
          hostPath:
            path: /home/utilities/lubelogger/log
            type: DirectoryOrCreate
        - name: keys
          hostPath:
            path: /home/utilities/lubelogger/keys
            type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/hostname: node1
---
apiVersion: v1
kind: Service
metadata:
  name: lubelogger
  labels:
    app: lubelogger
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: lubelogger
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lubelogger
  labels:
    app: lubelogger
  annotations:
    gethomepage.dev/description: Car Log
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Utilities
    gethomepage.dev/icon: lubelogger.png
    gethomepage.dev/name: lubelogger
    gethomepage.dev/pod-selector: app=lubelogger
    gethomepage.dev/weight: "20"
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway
    namespace: istio-ingress
    sectionName: https
  hostnames:
  - lubelogger.home.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: lubelogger
      port: 80
