---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: speedtest
  labels:
    app: speedtest
spec:
  selector:
    matchLabels:
      app: speedtest
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      containers:
      - image: ghcr.io/thisisqasim/speedtest-go:0.0.1
        imagePullPolicy: IfNotPresent
        name: speedtest
        ports:
        - containerPort: 8989
          name: http
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: http
            path: /empty
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest
  labels:
    app: speedtest
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: speedtest
  type: ClusterIP
  internalTrafficPolicy: Local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speedtest
  labels:
    app: speedtest
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: http://authentik-server.authentik.svc.cluster.local/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: https://authentik.home.com/outpost.goauthentik.io/start?rd=https://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-snippet: |
        proxy_set_header X-Forwarded-Host $http_host;
    nginx.ingress.kubernetes.io/auth-cache-key: $cookie_authentik_proxy_EhWySFtO
    nginx.ingress.kubernetes.io/auth-cache-duration: 200 202 10m, 401 5s
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    gethomepage.dev/description: LAN Bandwidth test
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Networking
    gethomepage.dev/icon: librespeed.png
    gethomepage.dev/name: Speedtest
    gethomepage.dev/pod-selector: app=speedtest
    gethomepage.dev/weight: "20"
spec:
  tls:
  - hosts:
    - speedtest.home.com
  rules:
  - host: speedtest.home.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: speedtest
            port:
              number: 80
