---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: speedtest
  labels:
    app: speedtest
spec:
  selector:
    matchLabels:
      app: speedtest
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      containers:
      - image: ghcr.io/thisisqasim/speedtest-go:0.0.11
        imagePullPolicy: IfNotPresent
        name: speedtest
        ports:
        - containerPort: 8989
          name: http
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: http
            path: /empty
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest
  labels:
    app: speedtest
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: speedtest
  type: ClusterIP
  internalTrafficPolicy: Local
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: speedtest
  labels:
    app: speedtest
  annotations:
    gethomepage.dev/description: LAN Bandwidth test
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Networking
    gethomepage.dev/icon: librespeed.png
    gethomepage.dev/name: Speedtest
    gethomepage.dev/pod-selector: app=speedtest
    gethomepage.dev/weight: "20"
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway
    namespace: istio-ingress
    sectionName: https
  hostnames:
  - speedtest.home.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        set:
        - name: X-Forwarded-Host
          value: speedtest.home.com
    backendRefs:
    - name: speedtest
      port: 80
