---
apiVersion: v1
kind: Service
metadata:
  name: spoofdpi
  labels:
    app: spoofdpi
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: y.y.y.y
  ports:
  - name: http-proxy
    port: 8080
    protocol: TCP
    targetPort: http-proxy
  selector:
    app: spoofdpi
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spoofdpi
  name: spoofdpi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spoofdpi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spoofdpi
    spec:
      containers:
      - image: ghcr.io/thisisqasim/spoofdpi:0.0.2
        name: spoofdpi
        args:
        - -addr=0.0.0.0
        - -window-size=1
        - -system-proxy=false
        - -dns-addr=pihole-dns.utilities.svc
        - -port=8080
        # - -debug
        ports:
        - containerPort: 8080
          name: http-proxy
          protocol: TCP          
        resources:
          requests:
            cpu: 100m
          limits:
            memory: 256Mi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node1
                - node3
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - spoofdpi
            topologyKey: "kubernetes.io/hostname"
