---
# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  # Create can not be restricted to a resource name.
  verbs: ["create"]
- apiGroups: [""] # "" indicates the core API group
  resourceNames: ["tailscale"]
  resources: ["secrets"]
  verbs: ["get", "update", "patch"]
---
# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
subjects:
- kind: ServiceAccount
  name: "tailscale"
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
---
# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tailscale
  name: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      serviceAccount: tailscale
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
      - image: ghcr.io/tailscale/tailscale
        name: sysctler
        securityContext:
          privileged: true
        command: ["/bin/sh"]
        args:
          - -c
          - sysctl -w net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1
      - name: modprobe
        image: ghcr.io/tailscale/tailscale
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /lib/modules
          readOnly: true
          name: modules
        command: ["/bin/sh"]
        args:
          - -c
          - modprobe tun ip_tables ip6_tables
      containers:
      - image: ghcr.io/tailscale/tailscale
        name: tailscale
        env:
        - name: TS_HOSTNAME
          value: f8k
        - name: TS_EXTRA_ARGS
          value: "--login-server https://headscale.project.com:443 --advertise-routes=y.y.y.y
        - name: TS_TAILSCALED_EXTRA_ARGS
          value: "--port=31643"
        - name: TS_KUBE_SECRET
          value: "tailscale"
        - name: TS_NAMESPACE
          value: "tailscale"
        - name: TS_USERSPACE
          value: "false"
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale
              key: TS_AUTHKEY
              optional: true
        - name: TS_ROUTES
          value: ""
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        resources:
          requests:
            cpu: 100m
          limits:
            memory: 512M
        volumeMounts:
        - mountPath: /dev/net/tun
          name: tun-device
      volumes:
      - name: tun-device
        hostPath:
          path: /dev/net/tun
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tailscale
  name: tailscale
  namespace: tailscale
spec:
  ports:
  - name: "tailscale"
    port: 31643
    protocol: UDP
    targetPort: 31643
  selector:
    app: tailscale
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: y.y.y.y
