---
# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  # Create can not be restricted to a resource name.
  verbs: ["create"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["events"]
  verbs: ["get", "create", "patch"]
- apiGroups: [""] # "" indicates the core API group
  resourceNames: ["tailscale"]
  resources: ["secrets"]
  verbs: ["get", "update", "patch"]
---
# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
subjects:
- kind: ServiceAccount
  name: "tailscale"
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
---
# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tailscale
  name: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tailscale
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ 
          "name" : "macvlan-conf",
          "namespace": "kube-system",
          "interface": "macvlan0",
          "ips": [ "y.y.y.y
          "default-route": ["y.y.y.y
        }]'
    spec:
      serviceAccount: tailscale
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
      - image: ghcr.io/tailscale/tailscale:v1.92.5
        imagePullPolicy: IfNotPresent
        name: sysctler
        securityContext:
          privileged: true
        command: ["/bin/sh"]
        args:
          - -c
          - sysctl -w net.ipv4.ip_forward=1 net.ipv4.conf.all.src_valid_mark=1
      - image: ghcr.io/tailscale/tailscale:v1.92.5
        imagePullPolicy: IfNotPresent
        name: modprobe
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /lib/modules
          readOnly: true
          name: modules
        command: ["/bin/sh"]
        args:
          - -c
          - modprobe tun
      containers:
      - image: ghcr.io/tailscale/tailscale:v1.92.5
        imagePullPolicy: IfNotPresent
        name: tailscale
        env:
        - name: TS_HOSTNAME
          value: f8k
        - name: TS_EXTRA_ARGS
          value: "--login-server https://headscale.home.com:443 --advertise-exit-node --accept-routes"
        - name: TS_TAILSCALED_EXTRA_ARGS
          value: "--port=31643"
        - name: TS_KUBE_SECRET
          value: "tailscale"
        - name: TS_NAMESPACE
          value: "tailscale"
        - name: TS_USERSPACE
          value: "false"
        - name: TS_SOCKS5_SERVER
          value: ":1055"
        - name: TS_OUTBOUND_HTTP_PROXY_LISTEN
          value: ":1080"
        - name: TS_DEBUG_FIREWALL_MODE
          value: "nftables"
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale
              key: TS_AUTHKEY
              optional: true
        - name: TS_ROUTES
          value: "y.y.y.y
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        resources:
          requests:
            cpu: 100m
            smarter-devices/net_tun: 1
          limits:
            memory: 512M
            smarter-devices/net_tun: 1
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node3
