apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  generators:
  - list:
      elements:
      - app: entertainment
      - app: nas
      - app: smarter-device-manager
      - app: oauth2-proxy
      - app: external-dns
      - app: utilities
  template:
    metadata:
      name: '{{app}}'
    spec:
      project: default
      source:
        repoURL: git@git.project.com/Qasim/infra.git
        targetRevision: main
        path: home/apps/{{app}}
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated: {}
        syncOptions:
        - Validate=true
        - CreateNamespace=true
