---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-server
  annotations:
    gethomepage.dev/description: GitOps
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Utilities
    gethomepage.dev/icon: argo-cd.png
    gethomepage.dev/name: Argocd
    gethomepage.dev/widget.type: argocd
    gethomepage.dev/widget.url: http://argocd-server.argocd.svc:80
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_ARGOCD_KEY}}"
    gethomepage.dev/pod-selector: >-
      app.kubernetes.io/name in (
          argocd-application-controller,
          argocd-applicationset-controller,
          argocd-dex-server,
          argocd-notifications-controller,
          argocd-redis,
          argocd-repo-server,
          argocd-server
      )
    gethomepage.dev/weight: "0"
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway
    namespace: istio-ingress
    sectionName: https
  hostnames:
  - argocd.home.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - group: ''
      kind: Service
      name: argocd-server
      port: 80
      weight: 1
