apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
    annotations:
        kustomize.config.k8s.io/needs-hash: "false"
        kustomize.config.k8s.io/behavior: replace
type: Opaque
data:
    admin.password: ENC[AES256_GCM,data:j9hLSEd9iMtYPgNsc2lJtvpJXA0XABxUlUAMLWdaMszCwph7ddv4eFtS+5/l+d1XLSVMWqFwD71a0m7FteG2eyHtHfFlZaJiNeiRibVHArk=,iv:qRPOa4TeCvpN4FKKLTxrZgglgoCxH7z/D94FjyPodN4=,tag:9QyOBlw8afH5ysPp0tCabA==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:JOflITi1Ekd7VjTjiQeL4IhbtPRb20Bu7MOGLw==,iv:jaEkGnBDKLsWaiavGVV9tkIO1TAee6MhfAfwG/RZkJk=,tag:7J0qW+2cNjBk/0oNoU+1Qw==,type:str]
    server.secretkey: ENC[AES256_GCM,data:li0BxHMHzDCqHaaZpzyB6xda95T6FYIpH9DKy0Z3AiglxQTpdZjET8wyyd3enXSWqW/gRckurBjl+z80,iv:Ok751R51modrYjvqSf27D20vfbC9kkqv7llsBJ/1Ojk=,tag:HmNbIppRWyZyKDKmjtA70A==,type:str]
    dex.authentik.clientSecret: ENC[AES256_GCM,data:CCpqPEFZhnxlL5WSgNxi+v6Qu9Ln9intCEnaKAQVwMHnCN9knxKqfDBouZ1zu8Zsc6tpkc6WxKNq6TPZxr45sw6Z9njTPtWDC5TjsCFrZ6UJz64C3tU6dE0NOaQigYh7xLB95EHI7eaW1WbQ7Ncg9/8l3ZNa9A9garrLLgPzStI8DjDGBTTO/gv83nZbQVDsCLcEDIZ14r2+bYnhtOUbUJS089YXWJ1p4M7MQw==,iv:01AAOHkWCOQKzAPCwSKRlbHBo9Qj3wECzYaYr5MZlBM=,tag:M5XQlX4osxMKr/ZUYpTqXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y5rqvlhmmfjs5xugxte9j4djl9ztk9v3w6n7sjg32pst5gw4vq5sey3mhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUUVJb2dkMkROYzQ4OGpm
            T0V4WkRJZUtOVGxZbE83VFoySmpDUkFIUjMwClhLTHk5cWNSUXBjb0lEQU9jVGVi
            VG12Tld4VFdNU01SUXN5MjZROWdKSUUKLS0tIGg2OHhCd0JuTUM5OEphYU1EODRh
            VUJ1Undlb2tMQU85SWVmbExFS0NxcjQKY3DbAwbw/NNGTy4TuEe8gZU11StggMew
            FCstQEJ7hfD8WN0xurQWrvMVER07Ofsemm5AXLPg9uWkuprtlk+4RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T14:57:52Z"
    mac: ENC[AES256_GCM,data:+R8A/0yhaqkiInM9R3OdBOG3ewK2rwZikZjRjbX5hKr87KDMjzjSd5wcTjLfpPx3cI/yFGm+ZMe9g/9tf/LY/fDe2/66gyQqmjvt14y3KCJsDlH+Dtl+scmFHB0j1ueP4R/1CNhIiqT0n5aDf2Es/wPfJeBQK0gFIh3zbXLFsCE=,iv:sGUIJ/1+LRuMvW1M2R++xBV2tNtr+xPx8i2CVS9LzUU=,tag:4sjaE5KPFH085bRRJBb/vA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
