apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true

resources:
- gateway.yaml
- auth-policies.yaml

helmCharts:
- name: base
  namespace: istio-system
  releaseName: istio-base
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.30.3
  includeCRDs: true
- name: istiod
  namespace: istio-system
  releaseName: istiod
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.30.3
  valuesFile: istiod.yaml
