apiVersion: v1
kind: Secret
metadata:
    name: infra-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
    annotations:
        kustomize.config.k8s.io/needs-hash: "false"
stringData:
    type: ENC[AES256_GCM,data:5AJU,iv:3kZNaEDAWiiWAJoW7P5MIg24il/pAnRhL15L9J47/Zc=,tag:NsXkP0uF20iqaiuQvktRbA==,type:str]
    name: ENC[AES256_GCM,data:RA61iIM=,iv:Ag5wp0xHr/KPtT1dy3/vPn/mUwuU6PmuLR2izZcjTm4=,tag:rlW2h6jvTWM0qNZlajexAg==,type:str]
    project: ENC[AES256_GCM,data:Tpz7Zop2pQ==,iv:TJ8GzVoZd85YdzyjYNxkrzFi5aqrHN1lMOYGZZMSjtE=,tag:GiMBNPQ/qfhX5w6koQq7EA==,type:str]
    url: ENC[AES256_GCM,data:diP59dX4kMo+yRtCupTb8XNifcfRwVw5KjmGMtj8F2+RSyknZVde,iv:KmlZBrcwvz/qD8mc2x/qRNEZchuV+HZUMmGdiNzGV6k=,tag:w3b5vrdGCHnOKDibJ70LQQ==,type:str]
    sshPrivateKey: ENC[AES256_GCM,data:ksWwClCXepf6VsxueTE3LT4xx7EUByS7ONFZE/s+wvDQuutd+D602fOxVcpzRl+vkgJxvGFsXcyFryGACkaI67tCPiY85HFpLXBsh809gh9V/JPyf2oA0U2DBG4gMfoh14rH9u8Ri4qE8MW+dTj7erD7S3YgioNTh03P+427ZG83Buhzht8q1YBndxaYQ/xAbpoVSFOEVzJf4HlKFlKlQVxb0VBUOvEhoNyHcOYZYWhaQ2ro/ipjngO4JOxxaHIE7V2I8bJAyQLS2783Rc7f4ejKP8U/1Ls/XKGqQbHg2BdGTCSkoxhw8sc8i6AwYMDjXneZAPwog0EzAneHmbjaRY7YoMmy6VJDZw9bU4kyLk1PDqiQl7skZYVrFGI2G01bVpLyxJJg49e2KE1Ik31n+xkPjujMkhgnEkDfpuYGkfSUYRNnTdjSMQrs91Vh53NSXqznCyFc4Y9fQo284eXFXWTZ+pMHLZnLLFFtXdwndzQWsdEviGrr5bWa4Ul9IowG7N7f7ypIKDzRR6XILoew4oEDNpW46kvrHzaNqNcNWnIozvbX1CFWIj9Z1RVyRuVA80xvh+X95+2+9zRqLZqxU5PcPomvyyROLhY58NqJZYDyQELUInfNF2RJiqdzTN83GZWMiv7I5UkVg1YoqUDvVy/YC6yoSbODdLetmRNBx4ld7ZPc7BAkkLcSD5Mi20Xh/8NviEFbQAWxsQxO2nm0usXfKiBPJavlEmVu47LXs1wIMUGM+hJ/vyCgvwMt2+k64nopjv4bk7Nip1dqPt6jZUzhOxg8hZq0537HHRqadCv3jRzMArD7OvMkmNVE1BJBuuspoFuBk8FJIH+feb9P35azSRRSvLN5hUSs2uivpd6wx8u2hjZeKAAH08a2I26wD8VDCBSqmFRc+HVDncyq3PE7hOfRN/h6YnQ+sikOVaTPoLaxgI+o06QsOQmQ1BK+hRdMQiBRuOkeVH65ayQacTmHDKZG4xdw/D41GSe6Uatq8ng6cmRvUng3A4IREuVIC2jOCXMUzuP2zT415nNSDdMYFCa7I55nXPlGKA8Fc5TMR39aJ1TsOnUScQYu6/X96JrRezRfNIO7ZgJ2+NxoI5E5tnc7Xn9JBruMjdIqahb8RdasBQxuFWqY6R9gWweJ/9It6N317BG8wifGVyQruXDiqEoqgHin6UVlKjOpcXMy8ab7pIrffbafOS/C+LS++3UO8I0cIJMU2cmPnJpRcad7pEATNL8a2K+I3q65Hhe1tXTPxc3OtOs1Y3r6MFjRfsxNdY11BfauZF4WHT+87iA7zfJj3Mm+io7hRDLXqwmqxDOBf6fMjpXC9dwXVeaUGbu/R9f/pOU/M3iY2it8In0se//steMFtAyJiybmmBB3g71aEnrR60xSZlgm9e1zvdSH77tWShKUZOc+7+thjslMhVRuv1Iz5ksao4piAjubBJTAsFWx+gDxgnw5oHL9C416piaESJwDONWb+pNHiqmFnfpm2YGfMekXHXLK5UrTIgdV+kTwpsuNM4XjME+HO8if3kxQWZ6F4clI6oeqLGhivacZidtoYyWajIh6QE/FdnE4xnQxp55CL9ef51KEIEa6AOmGeMdbcoWTL0RwfetivR7g3oIR4/gaMCVZ0aBzujuM06gmKMBT8lfXSwv63SFzvklq6wexCRZke7NXEaNjbkh5YnTdJtc5Pt9l1+UKOFnVGdvmMWh1kYCn30B1eA+irjCJKVv/X0t8syMQ9EwdzOL0cI+oGN0+jNf8u+AVRzFIgS+l6Ksy6RxzUkzSnbi5X9uCdKBF6RBl6pYQcTsF6Xbp1Q/xHnI3NPSKHetmcpjO32MC833s4/2/+t/20AmKYjR1QY5afHP5sfijg46enqFk1LD2YNiDVuew7qf+UrQISzDvIps1ua1PolZb5PY0ZYRI+uC9e4f2Pp+LJP7oGAz2TNZWLEMYGJAMcG2Oe1Tk7URX3HsTYaR0kmspuWydDYTo024/DmkqCLO37+9ZzkVGwXEakS8GzDUeB3vgxQl+nOUrPqBMKRdIXltySWqQ5gLpySCeadG4Sc3fkNjPVV01tOc7izIjQB5Uvi4v6s3AyUEkE33KhhOUcW4EAN6owyRx9YIxA9tlHh78WJtxoNqpjkzKGVv+Hgt3w3jAx5g6DoHfDo6NiIIZtR63gB7jFG2C4d/knls83SZSYGBdUe+0ziWnUwsKuRUVDU2KsXDiQMBW8sWKGhBrDZM=,iv:QVpOhfCvla75m+ytiVCZrtjhWan8KRuY0ZCPGris3Xw=,tag:fRSgyWItIgKL3N4nTq30Ow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y5rqvlhmmfjs5xugxte9j4djl9ztk9v3w6n7sjg32pst5gw4vq5sey3mhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUzNIR2RvaTcvYXl1WmFU
            VC9GMVlTSitTY3F3SFpEL3duOXNhUlNRT0djClVDRitPNzVGbGVKK3NlR0N4UHpP
            aFRXSUc1SU0ybnB6MWZOMTB2V2dpMFkKLS0tIGFBcGg5djAwUzVNaGtHQTNydExv
            T2IxYk1PMHRjeEphWjFrTTV5NU1YNkEKiSxBD5uZiMNFFjxUTzkTwsOwUsNqkxFx
            7Hm44YwhoG2XBVGJWBZPh4WevxSDA5w+HqsT8ePz/3PKQX9gx4IvfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-13T08:22:18Z"
    mac: ENC[AES256_GCM,data:LG9rtIG0hmk7EplrjSkeduHQun4oVIGZaz4LQE3XUZ0bVCZuenCr706QMLNwCvro1NghK2E9CfPWVITILeurk153Lwzwf7NZkev2X7FYBupNqGYmbrPOgkYciaK1xNSIo++MP7zDvQ+xidyum71ge+WEsCNNLceNtTQ4L65Ts5k=,iv:TmfkGQEjE9G+2+esStc90Wj63EmrTinqCoawR4IRgmU=,tag:rlTf0C9zSbiud7XBb3fiYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
