apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: entertainment
resources:
- namespace.yaml
- heimdall.yaml
- jellyfin.yaml
- sonarr.yaml
- radarr.yaml
- jackett.yaml
- ombi.yaml
- transmission.yaml
- metube.yaml
