---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: entertainment
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - image: lscr.io/linuxserver/radarr:latest
        name: radarr
        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "Asia/Karachi"
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data
          name: media
        ports:
        - containerPort: 8989
        livenessProbe:
          tcpSocket:
            port: 8989
          initialDelaySeconds: 600
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 8989
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "2560Mi"
      volumes:
        - name: config
          hostPath:
            path: /home/entertainment/radarr
            type: Directory
        - name: media
          hostPath:
            path: /mnt/external/media
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: entertainment
  labels:
    app: radarr
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8989
  selector:
    app: radarr
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  namespace: entertainment
  labels:
    app: radarr
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - secretName: radarr-tls
    hosts:
    - radarr.home.com
  rules:
  - host: radarr.home.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              number: 80
