---
apiVersion: v1
kind: ConfigMap
metadata:
  name: avahi
data:
  avahi-daemon.conf: |
    [server]
    use-ipv4=yes
    use-ipv6=no
    allow-interfaces=enp0s31f6,eno1
    enable-dbus=yes
    ratelimit-interval-usec=1000000
    ratelimit-burst=1000

    [wide-area]
    enable-wide-area=yes

    [publish]
    publish-hinfo=no
    publish-workstation=no

  smb.service: |
    <?xml version="1.0" standalone='no'?>
    <!DOCTYPE service-group SYSTEM "avahi-service.dtd">
    <service-group>
     <name replace-wildcards="yes">%h</name>
     <service>
       <type>_adisk._tcp</type>
       <txt-record>sys=waMa=0,adVF=0x100</txt-record>
       <txt-record>dk0=adVN=TimeCapsule,adVF=0x82</txt-record>
     </service>
     <service>
        <type>_smb._tcp</type>
        <port>445</port>
     </service>
     <service>
       <type>_device-info._tcp</type>
       <port>0</port>
       <txt-record>model=Macmini6</txt-record>
     </service>
    </service-group>
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: avahi
  labels:
    app: avahi
spec:
  selector:
    matchLabels:
      app: avahi
  template:
    metadata:
      labels:
        app: avahi
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
      - image: thisisqasim/avahi:latest
        imagePullPolicy: Always
        name: clearpid
        command: ["rm","-rf","/run/avahi-daemon/pid","/run/avahi-daemon/socket"]
        volumeMounts:
        - mountPath: /run/avahi-daemon
          subPath: avahi-daemon
          name: run
      containers:
      - image: thisisqasim/avahi:latest
        imagePullPolicy: Always
        name: avahi
        command: ["avahi-daemon","--no-chroot","--no-proc-title","--no-drop-root","-f","/etc/avahi/avahi-daemon.conf"]
        volumeMounts:
        - mountPath: /etc/avahi/avahi-daemon.conf
          subPath: avahi-daemon.conf
          name: config
        - mountPath: /etc/avahi/services/smb.service
          subPath: smb.service
          name: config
        - mountPath: /run/avahi-daemon
          subPath: avahi-daemon
          name: run
        - name: dbus-socket
          mountPath: /run/dbus/system_bus_socket
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - test -S /run/avahi-daemon/socket
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - test -S /run/avahi-daemon/socket
        resources:
          requests:
            cpu: "10m"
          limits:
            memory: "64Mi"
      volumes:
      - name: config
        configMap:
          name: avahi
      - name: run
        hostPath:
          path: /host/run
          type: DirectoryOrCreate
      - name: dbus-socket
        hostPath:
          path: /host/run/dbus/system_bus_socket
          type: Socket
