apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nas
resources:
- namespace.yaml
- samba.yaml
- dbus.yaml
- avahi.yaml
- mysql.yaml
- nextcloud.yaml
- redis.yaml
- speedtest.yaml

generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: secrets
    secretFrom:
    - metadata:
        name: mysql
        annotations:
          kustomize.config.k8s.io/needs-hash: "true"
      envs:
      - ./mysql.enc.env
    - metadata:
        name: samba-password
        annotations:
          kustomize.config.k8s.io/needs-hash: "true"
      envs:
      - ./samba.enc.env
