---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  ports:
  - port: 9000
    name: http
    targetPort: http
  - port: 9001
    name: console
    targetPort: console
  type: ClusterIP
  selector:
    app: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:RELEASE.2024-09-13T20-26-02Z
        imagePullPolicy: IfNotPresent
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        env:
        - name: MINIO_REGION
          value: eu-central-1
        - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
          value: policy
        envFrom:
        - secretRef:
            name: minio        
        resources:
          requests:
            cpu: 200m
          limits:
            memory: "1.2Gi"
        ports:
        - containerPort: 9000
          name: http
        - containerPort: 9001
          name: console
        readinessProbe:
          tcpSocket:
            port: 9000
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1001
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
        - name: data
          hostPath:
            path: /mnt/external/s3
            type: Directory
      enableServiceLinks: false
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
        runAsGroup: 1001
      nodeSelector:
        kubernetes.io/hostname: node3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console
  labels:
    app: minio
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    gethomepage.dev/description: Object Storage
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Utilities
    gethomepage.dev/icon: minio.png
    gethomepage.dev/name: MinIO
    gethomepage.dev/pod-selector: app=minio
    gethomepage.dev/weight: "90"
spec:
  tls:
  - hosts:
    - minio.home.com
  rules:
  - host: minio.home.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              name: console
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  labels:
    app: minio
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/server-snippet: |
      ignore_invalid_headers off;
    nginx.ingress.kubernetes.io/configuration-snippet: |
      chunked_transfer_encoding off;
      proxy_set_header  Accept-Encoding  "identity";
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  tls:
  - hosts:
    - s3.home.com
  rules:
  - host: s3.home.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              name: http
