---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  ports:
  - port: 8080
    name: http
    targetPort: http
  - port: 7867
    name: push
    targetPort: push
  type: ClusterIP
  selector:
    app: nextcloud
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud
data:
  ports.conf: |
    Listen 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: public.ecr.aws/docker/library/nextcloud:29.0.7
        imagePullPolicy: IfNotPresent
        env:
        - name: PHP_MEMORY_LIMIT
          value: 1G
        resources:
          requests:
            cpu: 200m
            memory: "2Gi"
          limits:
            memory: "4Gi"
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          tcpSocket:
            port: 8080
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1001
        volumeMounts:
        - name: ports
          mountPath: /etc/apache2/ports.conf
          subPath: ports.conf
        - name: external
          mountPath: /external
        - name: custom-apps
          mountPath: /var/www/html/custom_apps
        - name: config
          mountPath: /var/www/html/config
        - name: data
          mountPath: /var/www/html/data
        - name: nextcloud
          mountPath: /var/www/html
      - name: push
        image: public.ecr.aws/docker/library/nextcloud:29.0.7
        imagePullPolicy: IfNotPresent
        command:
        - /var/www/html/custom_apps/notify_push/bin/x86_64/notify_push
        - /var/www/html/config/config.php
        env:
        - name: NEXTCLOUD_URL
          value: http://nextcloud:8080
        resources:
          requests:
            cpu: 50m
          limits:
            memory: "256Mi"
        ports:
        - containerPort: 7867
          name: push
        readinessProbe:
          tcpSocket:
            port: 7867
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1001
        volumeMounts:
        - name: external
          mountPath: /external
        - name: custom-apps
          mountPath: /var/www/html/custom_apps
        - name: config
          mountPath: /var/www/html/config
        - name: data
          mountPath: /var/www/html/data
      - name: cron
        image: public.ecr.aws/docker/library/nextcloud:29.0.7
        imagePullPolicy: IfNotPresent
        command:
        - /bin/bash
        - -c
        - |
          set -eu
          until ls /var/www/html/lib/versioncheck.php; do sleep 1; done
          ./occ maintenance:update:htaccess
          ./occ upgrade
          ./occ db:add-missing-columns
          ./occ db:add-missing-primary-keys
          ./occ db:add-missing-indices
          ./occ maintenance:mimetype:update-db
          ./occ maintenance:mimetype:update-js
          ./occ maintenance:repair
          ./occ maintenance:update:htaccess
          while sleep 300;do php -f cron.php; done
        env:
        - name: PHP_MEMORY_LIMIT
          value: 1G
        resources:
          requests:
            cpu: 50m
          limits:
            memory: "256Mi"
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1001
        volumeMounts:
        - name: external
          mountPath: /external
        - name: custom-apps
          mountPath: /var/www/html/custom_apps
        - name: config
          mountPath: /var/www/html/config
        - name: data
          mountPath: /var/www/html/data
        - name: nextcloud
          mountPath: /var/www/html
      volumes:
        - name: ports
          configMap:
            name: nextcloud
        - name: external
          hostPath:
            path: /mnt/external
            type: Directory
        - name: custom-apps
          hostPath:
            path: /home/nas/nextcloud/custom_apps
            type: Directory
        - name: config
          hostPath:
            path: /home/nas/nextcloud/config
            type: Directory
        - name: data
          hostPath:
            path: /home/nas/nextcloud/data
            type: Directory
        - name: nextcloud
          emptyDir: {}
      enableServiceLinks: false
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      nodeSelector:
        kubernetes.io/hostname: node3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
  labels:
    app: nextcloud
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    gethomepage.dev/description: File Storage
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Utilities
    gethomepage.dev/icon: nextcloud.png
    gethomepage.dev/name: Nextcloud
    gethomepage.dev/pod-selector: app=nextcloud
    gethomepage.dev/weight: "10"
    gethomepage.dev/widget.type: nextcloud
    gethomepage.dev/widget.url: http://nextcloud.nas.svc:8080
    gethomepage.dev/widget.username: "{{HOMEPAGE_VAR_NEXTCLOUD_USERNAME}}"
    gethomepage.dev/widget.password: "{{HOMEPAGE_VAR_NEXTCLOUD_PASSWORD}}"
spec:
  tls:
  - hosts:
    - cloud.home.com
  rules:
  - host: cloud.home.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud
            port:
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-push
  labels:
    app: nextcloud
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  tls:
  - hosts:
    - cloud.home.com
  rules:
  - host: cloud.home.com
    http:
      paths:
      - path: /push
        pathType: Prefix
        backend:
          service:
            name: nextcloud
            port:
              number: 7867
