apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oauth2-proxy

resources:
- namespace.yaml
- legacy.yaml
- ups.yaml

helmChartInflationGenerator:
- chartName: oauth2-proxy
  chartRepoUrl: https://oauth2-proxy.github.io/manifests
  chartVersion: 6.12.0
  releaseName: oauth2-proxy
  values: values.yaml


generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: secrets
    files:
      - ./oauth2-proxy.enc.yaml
