---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate
  labels:
    app: frigate
data:
  config.yml: |
    mqtt:
      host: mqtt
      port: 1883
      user: mqtt
      password: "{FRIGATE_MQTT_PASSWORD}"
    ui:
      live_mode: webrtc
    logger:
      default: info
      logs:
        frigate.app: debug
        frigate.mqtt: debug
        frigate.object_detection: debug
    detectors:
      coral1:
        type: edgetpu
        device: pci:0
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
      - person
      - car
      - motorcycle
      - bicycle
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 30
          mode: active_objects
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
    go2rtc:
      streams:
        hikvision-1:
        - rtsp://admin:{FRIGATE_HIKVISION_PASSWORD}@y.y.y.y
        hikvision-2:
        - rtsp://admin:{FRIGATE_HIKVISION_PASSWORD}@y.y.y.y
        hikvision-3:
        - rtsp://admin:{FRIGATE_HIKVISION_PASSWORD}@y.y.y.y
        hikvision-4:
        - rtsp://admin:{FRIGATE_HIKVISION_PASSWORD}@y.y.y.y
        hikvision-5:
        - rtsp://admin:{FRIGATE_HIKVISION_PASSWORD}@y.y.y.y
        hikvision-6:
        - rtsp://admin:{FRIGATE_HIKVISION_PASSWORD}@y.y.y.y
        hikvision-7:
        - rtsp://admin:{FRIGATE_HIKVISION_PASSWORD}@y.y.y.y
        hikvision-8:
        - rtsp://admin:{FRIGATE_HIKVISION_PASSWORD}@y.y.y.y
        pollo-1:
        - rtsp://admin:{FRIGATE_POLLO_PASSWORD}@y.y.y.y
        - "ffmpeg:pollo-1#audio=aac"
      webrtc:
        candidates:
        - y.y.y.y
        - stun:18555
    cameras:
      # Define at least one camera
      hikvision-1:
        ffmpeg:
          inputs:
          - path: rtsp://127.0.0.1:8554/hikvision-1
            roles:
            - record
          - path: rtsp://admin:{FRIGATE_HIKVISION_PASSWORD}@y.y.y.y
            roles:
            - detect
        motion:
          mask:
          - 316,0,373,0,372,35,317,32
      hikvision-2:
        ffmpeg:
          inputs:
          - path: rtsp://127.0.0.1:8554/hikvision-2
            roles:
            - record
          - path: rtsp://admin:{FRIGATE_HIKVISION_PASSWORD}@y.y.y.y
            roles:
            - detect
        motion:
          mask:
          - 1280,409,716,164,449,108,0,78,0,0,1280,0
        objects:
          track:
          - person
          filters:
            person:
              mask:
              - 1280,409,716,164,449,108,0,78,0,0,1280,0
      hikvision-3:
        ffmpeg:
          inputs:
          - path: rtsp://127.0.0.1:8554/hikvision-3
            roles:
            - record
          - path: rtsp://admin:{FRIGATE_HIKVISION_PASSWORD}@y.y.y.y
            roles:
            - detect
        objects:
          track:
          - person
        motion:
          mask:
          - 332,21,367,21,367,51,329,50
      hikvision-4:
        ffmpeg:
          inputs:
          - path: rtsp://127.0.0.1:8554/hikvision-4
            roles:
            - record
          - path: rtsp://admin:{FRIGATE_HIKVISION_PASSWORD}@y.y.y.y
            roles:
            - detect
        motion:
          mask:
          - 330,21,374,21,375,47,330,46
      hikvision-5:
        ffmpeg:
          inputs:
          - path: rtsp://127.0.0.1:8554/hikvision-5
            roles:
            - record
          - path: rtsp://admin:{FRIGATE_HIKVISION_PASSWORD}@y.y.y.y
            roles:
            - detect
        motion:
          mask:
          - 1280,0,1280,70,623,99,0,181,0,0
      hikvision-6:
        ffmpeg:
          inputs:
          - path: rtsp://127.0.0.1:8554/hikvision-6
            roles:
            - record
          - path: rtsp://admin:{FRIGATE_HIKVISION_PASSWORD}@y.y.y.y
            roles:
            - detect
        motion:
          mask:
          - 1280,0,1280,266,570,0
          - 329,21,368,21,370,50,339,54
        objects:
          track:
          - person
      hikvision-7:
        ffmpeg:
          inputs:
          - path: rtsp://127.0.0.1:8554/hikvision-7
            roles:
            - record
          - path: rtsp://admin:{FRIGATE_HIKVISION_PASSWORD}@y.y.y.y
            roles:
            - detect
        motion:
          mask:
          - 330,0,374,0,378,28,333,31
      hikvision-8:
        ffmpeg:
          inputs:
          - path: rtsp://127.0.0.1:8554/hikvision-8
            roles:
            - record
          - path: rtsp://admin:{FRIGATE_HIKVISION_PASSWORD}@y.y.y.y
            roles:
            - detect
        objects:
          track:
          - person
        motion:
          mask:
          - 372,52,369,0,322,0,326,49
      pollo-1:
        ffmpeg:
          inputs:
          - path: rtsp://127.0.0.1:8554/pollo-1
            roles:
            - record
          - path: rtsp://admin:{FRIGATE_POLLO_PASSWORD}@y.y.y.y
            roles:
            - detect
        detect:
          width: 640
          height: 360
        objects:
          track:
          - person
        motion:
          mask:
          - 487,0,478,63,404,41,279,55,282,0
          - 149,0,173,0,171,32,152,31
---
apiVersion: v1
kind: Service
metadata:
  name: frigate
  labels:
    app: frigate
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: http
  selector:
    app: frigate
---
apiVersion: v1
kind: Service
metadata:
  name: frigate-webrtc
  labels:
    app: frigate
  annotations:
    kube-vip.io/loadbalancerIPs: y.y.y.y
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: webrtc-tcp
      port: 8555
      protocol: TCP
      targetPort: webrtc-tcp
    - name: webrtc-udp
      port: 8555
      protocol: UDP
      targetPort: webrtc-udp
  selector:
    app: frigate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  labels:
    app: frigate
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      containers:
      - name: frigate
        image: "ghcr.io/blakeblackshear/frigate:0.13.2"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        - name: webrtc-tcp
          containerPort: 8555
          protocol: TCP
        - name: webrtc-udp
          containerPort: 8555
          protocol: UDP
        startupProbe:
          failureThreshold: 20
          httpGet:
            path: /api/version
            port: http
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /api/version
            port: http
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /api/version
            port: http
            scheme: HTTP
        env:
        - name: LIBVA_DRIVER_NAME
          value: i965
        envFrom:
        - secretRef:
            name: frigate
        volumeMounts:
          - name: config
            mountPath: /config/config.yml
            subPath: config.yml
          - name: media
            mountPath: /config
            subPath: config
          - name: media
            mountPath: /media/frigate
          - name: recordings
            mountPath: /media/frigate/recordings
          - name: clips
            mountPath: /media/frigate/clips
          - name: exports
            mountPath: /media/frigate/exports
          - name: dshm
            mountPath: /dev/shm
        resources:
          requests:
            cpu: "1.5"
            memory: "3Gi"
            smarter-devices/dri_card0: 1
            smarter-devices/dri_renderD128: 1
            smarter-devices/apex_0: 1
          limits:
            memory: "6Gi"
            smarter-devices/dri_card0: 1
            smarter-devices/dri_renderD128: 1
            smarter-devices/apex_0: 1
        securityContext:
          capabilities:
            add: ["SYS_ADMIN", "CAP_PERFMON"]
      volumes:
      - name: config
        configMap:
          name: frigate
      - name: media
        hostPath:
          path: /home/ha/frigate
          type: Directory
      - name: recordings
        hostPath:
          path: /mnt/external/backups/recordings
          type: Directory
      - name: clips
        hostPath:
          path: /mnt/external/backups/clips
          type: Directory
      - name: exports
        hostPath:
          path: /mnt/external/backups/exports
          type: Directory
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
      nodeSelector:
        disk-type: recordings
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frigate
  labels:
    app: frigate
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-signin: https://iap.home.com/oauth2/start?rd=https://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.utilities.svc.cluster.local/oauth2/auth
    nginx.ingress.kubernetes.io/auth-cache-key: $cookie__oauth2_proxy
    nginx.ingress.kubernetes.io/auth-cache-duration: 200 202 10m, 401 0m
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    gethomepage.dev/description: NVR
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Home Automation
    gethomepage.dev/icon: frigate-light.png
    gethomepage.dev/name: Frigate
    gethomepage.dev/pod-selector: app=frigate
    gethomepage.dev/weight: "0"
spec:
  tls:
  - hosts:
    - frigate.home.com
  rules:
  - host: frigate.home.com
    http:
      paths:
        - path: /
          pathType: "ImplementationSpecific"
          backend:
            service:
              name: frigate
              port:
                name: http
