---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homebridge
  name: homebridge
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homebridge
  template:
    metadata:
      labels:
        app: homebridge
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name" : "macvlan-conf", "namespace": "kube-system", "interface": "macvlan0", "ips": [ "y.y.y.y
          { "name" : "macvlan-iot", "namespace": "kube-system", "interface": "macvlan1", "ips": [ "y.y.y.y
    spec:
      containers:
      - name: homebridge
        image: "ghcr.io/homebridge/homebridge:2025-09-28"
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
        env:
        - name: TZ
          value: Asia/Karachi
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: HOMEBRIDGE_CONFIG_UI
          value: "1"
        - name: HOMEBRIDGE_CONFIG_UI_PORT
          value: "8581"
        - name: ENABLE_AVAHI
          value: "1"
        ports:
        - name: http
          containerPort: 8581
          protocol: TCP
        - name: metrics
          containerPort: 36123
          protocol: TCP
        resources:
          requests:
            cpu: "200m"
          limits:
            memory: "1Gi"
        livenessProbe:
          tcpSocket:
            port: 8581
        readinessProbe:
          httpGet:
            port: 8581
        volumeMounts:
        - name: data
          mountPath: /homebridge
      restartPolicy: Always
      volumes:
      - name: data
        hostPath:
          path: /home/ha/homebridge
          type: Directory
      nodeSelector:
        kubernetes.io/hostname: node2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homebridge
  name: homebridge
spec:
  type: ClusterIP
  ports:
  - port: 8581
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: homebridge
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homebridge
  labels:
    app: homebridge
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: http://authentik-server.authentik.svc.cluster.local/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: https://authentik.home.com/outpost.goauthentik.io/start?rd=https://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-snippet: |
        proxy_set_header X-Forwarded-Host $http_host;
    nginx.ingress.kubernetes.io/auth-cache-key: $cookie_authentik_proxy_EhWySFtO
    nginx.ingress.kubernetes.io/auth-cache-duration: 200 202 10m, 401 5s
    gethomepage.dev/description: HomeKit bridge
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Home Automation
    gethomepage.dev/icon: homebridge.png
    gethomepage.dev/name: Homebridge
    gethomepage.dev/pod-selector: app=homebridge
    gethomepage.dev/weight: "30"
    gethomepage.dev/widget.type: homebridge
    gethomepage.dev/widget.url: http://homebridge.ha.svc:8581
    gethomepage.dev/widget.username: "{{HOMEPAGE_VAR_HOMEBRIDGE_USERNAME}}"
    gethomepage.dev/widget.password: "{{HOMEPAGE_VAR_HOMEBRIDGE_PASSWORD}}"
spec:
  tls:
  - hosts:
    - homebridge.home.com
  rules:
  - host: homebridge.home.com
    http:
      paths:
        - path: /
          pathType: "ImplementationSpecific"
          backend:
            service:
              name: homebridge
              port:
                name: http
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: homebridge
  labels:
    app: homebridge
    release: prometheus
spec:
  selector:
    matchLabels:
      app: homebridge
  podMetricsEndpoints:
  - port: metrics
    basicAuth:
      password:
        name: prometheus
        key: password
      username:
        name: prometheus
        key: username
