---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homebridge
  name: homebridge
spec:
  type: ClusterIP
  ports:
  - port: 8581
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: homebridge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homebridge
  name: homebridge
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homebridge
  template:
    metadata:
      labels:
        app: homebridge
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: homebridge
        image: "ghcr.io/homebridge/homebridge:latest"
        imagePullPolicy: Always
        securityContext:
          privileged: false
        env:
        - name: TZ
          value: Asia/Karachi
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: HOMEBRIDGE_CONFIG_UI
          value: "1"
        - name: HOMEBRIDGE_CONFIG_UI_PORT
          value: "8581"
        - name: ENABLE_AVAHI
          value: "1"
        ports:
          - name: http
            containerPort: 8581
            protocol: TCP
        resources:
          requests:
            cpu: "1"
          limits:
            memory: "2Gi"
        livenessProbe:
          tcpSocket:
            port: 8581
        readinessProbe:
          httpGet:
            port: 8581
        volumeMounts:
        - name: data
          mountPath: /homebridge
      restartPolicy: Always
      volumes:
      - name: data
        hostPath:
          path: /home/ha/homebridge
          type: Directory
      nodeSelector:
        disk-type: backups
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homebridge
  labels:
    app: homebridge
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-signin: https://iap.home.com/oauth2/start?rd=https://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.utilities.svc.cluster.local/oauth2/auth
    nginx.ingress.kubernetes.io/auth-cache-key: $cookie__oauth2_proxy
    nginx.ingress.kubernetes.io/auth-cache-duration: 200 202 10m, 401 0m
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    gethomepage.dev/description: HomeKit Secure Video Bridge
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Home Automation
    gethomepage.dev/icon: homebridge.png
    gethomepage.dev/name: homebridge
    gethomepage.dev/weight: "10"
spec:
  tls:
  - hosts:
    - homebridge.home.com
  rules:
  - host: homebridge.home.com
    http:
      paths:
        - path: /
          pathType: "ImplementationSpecific"
          backend:
            service:
              name: homebridge
              port:
                name: http
