---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scrypted
  name: scrypted
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: scrypted
  template:
    metadata:
      labels:
        app: scrypted
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "name" : "macvlan-conf", "namespace": "kube-system", "interface": "macvlan0", "ips": [ "y.y.y.y
    spec:
      containers:
      - name: scrypted
        image: "ghcr.io/koush/scrypted:v0.144.1-noble-full"
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
        env:
        - name: SCRYPTED_DOCKER_AVAHI
          value: "true"
        envFrom:
        - secretRef:
            name: scrypted
        ports:
          - name: http
            containerPort: 11080
            protocol: TCP
        resources:
          requests:
            cpu: "1"
            smarter-devices/dri_card0: 1
            smarter-devices/dri_renderD128: 1
          limits:
            memory: "8Gi"
            smarter-devices/dri_card0: 1
            smarter-devices/dri_renderD128: 1
        livenessProbe:
          tcpSocket:
            port: 11080
        readinessProbe:
          tcpSocket:
            port: 11080
        volumeMounts:
        - name: data
          mountPath: /server/volume
      restartPolicy: Always
      volumes:
      - name: data
        hostPath:
          path: /home/ha/scrypted
          type: Directory
      nodeSelector:
        kubernetes.io/hostname: node2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: scrypted
  name: scrypted
spec:
  type: ClusterIP
  ports:
  - port: 11080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: scrypted
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: scrypted
  labels:
    app: scrypted
  annotations:
    gethomepage.dev/description: HomeKit Secure Video Bridge
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Home Automation
    gethomepage.dev/icon: scrypted.png
    gethomepage.dev/name: Scrypted
    gethomepage.dev/pod-selector: app=scrypted
    gethomepage.dev/weight: "10"
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway
    namespace: istio-ingress
    sectionName: https
  hostnames:
  - scrypted.home.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: scrypted
      port: 11080
