---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: scrypted
  name: scrypted
spec:
  type: ClusterIP
  ports:
  - port: 11080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: scrypted
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scrypted
  name: scrypted
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: scrypted
  template:
    metadata:
      labels:
        app: scrypted
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: scrypted
        image: "ghcr.io/koush/scrypted:full"
        imagePullPolicy: Always
        securityContext:
          privileged: false
        env:
        - name: DEBUG
          value: "HAP-NodeJS:*"
        envFrom:
        - secretRef:
            name: scrypted
        ports:
          - name: http
            containerPort: 11080
            protocol: TCP
        resources:
          requests:
            cpu: "1"
            smarter-devices/dri_card0: 1
            smarter-devices/dri_renderD128: 1
            smarter-devices/apex_0: 1
          limits:
            memory: "5Gi"
            smarter-devices/dri_card0: 1
            smarter-devices/dri_renderD128: 1
            smarter-devices/apex_0: 1
        livenessProbe:
          tcpSocket:
            port: 11080
        readinessProbe:
          tcpSocket:
            port: 11080
        volumeMounts:
        - name: data
          mountPath: /server/volume
        - name: run
          mountPath: /var/run/avahi-daemon
          subPath: avahi-daemon
        - name: run
          mountPath: /run/dbus
          subPath: dbus
      restartPolicy: Always
      volumes:
      - name: data
        hostPath:
          path: /home/ha/scrypted
          type: Directory
      - name: run
        hostPath:
          path: /host/run
          type: Directory
      nodeSelector:
        disk-type: recordings
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scrypted
  labels:
    app: scrypted
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-signin: https://iap.home.com/oauth2/start?rd=https://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.utilities.svc.cluster.local/oauth2/auth
    nginx.ingress.kubernetes.io/auth-cache-key: $cookie__oauth2_proxy
    nginx.ingress.kubernetes.io/auth-cache-duration: 200 202 10m, 401 0m
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    gethomepage.dev/description: HomeKit Secure Video Bridge
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Home Automation
    gethomepage.dev/icon: scrypted.png
    gethomepage.dev/name: Scrypted
    gethomepage.dev/weight: "10"
spec:
  tls:
  - hosts:
    - scrypted.home.com
  rules:
  - host: scrypted.home.com
    http:
      paths:
        - path: /
          pathType: "ImplementationSpecific"
          backend:
            service:
              name: scrypted
              port:
                name: http
