apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      containers:
      - image: koenkk/zigbee2mqtt:2.1.3
        imagePullPolicy: IfNotPresent
        name: zigbee2mqtt
        env:
        - name: TZ
          value: 'Asia/Karachi'
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: "100m"
            smarter-devices/ttyUSB0: 1
          limits:
            memory: "1Gi"
            smarter-devices/ttyUSB0: 1
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: udev
          mountPath: /run/udev
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: data
        hostPath:
          path: /home/ha/zigbee2mqtt
          type: DirectoryOrCreate
      - name: udev
        hostPath:
          path: /run/udev
          type: Directory
      nodeSelector:
        kubernetes.io/hostname: node2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: zigbee2mqtt
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zigbee2mqtt
  labels:
    app: zigbee2mqtt
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: http://authentik-server.authentik.svc.cluster.local/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: https://authentik.home.com/outpost.goauthentik.io/start?rd=https://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-snippet: |
        proxy_set_header X-Forwarded-Host $http_host;
    nginx.ingress.kubernetes.io/auth-cache-key: $cookie_authentik_proxy_EhWySFtO
    nginx.ingress.kubernetes.io/auth-cache-duration: 200 202 10m, 401 5s
    gethomepage.dev/description: Zigbee to MQTT
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Home Automation
    gethomepage.dev/icon: zigbee2mqtt.png
    gethomepage.dev/name: Zigbee2MQTT
    gethomepage.dev/pod-selector: app=zigbee2mqtt
    gethomepage.dev/weight: "40"
spec:
  tls:
  - hosts:
    - zigbee2mqtt.home.com
  rules:
  - host: zigbee2mqtt.home.com
    http:
      paths:
        - path: /
          pathType: "ImplementationSpecific"
          backend:
            service:
              name: zigbee2mqtt
              port:
                name: http
