apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      containers:
      - image: koenkk/zigbee2mqtt:2.11.0
        imagePullPolicy: IfNotPresent
        name: zigbee2mqtt
        env:
        - name: TZ
          value: 'Asia/Karachi'
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: "100m"
            smarter-devices/ttyUSB0: 1
          limits:
            memory: "1Gi"
            smarter-devices/ttyUSB0: 1
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: udev
          mountPath: /run/udev
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: data
        hostPath:
          path: /home/ha/zigbee2mqtt
          type: DirectoryOrCreate
      - name: udev
        hostPath:
          path: /run/udev
          type: Directory
      nodeSelector:
        kubernetes.io/hostname: node2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: zigbee2mqtt
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: zigbee2mqtt
  labels:
    app: zigbee2mqtt
  annotations:
    gethomepage.dev/description: Zigbee to MQTT
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Home Automation
    gethomepage.dev/icon: zigbee2mqtt.png
    gethomepage.dev/name: Zigbee2MQTT
    gethomepage.dev/pod-selector: app=zigbee2mqtt
    gethomepage.dev/weight: "40"
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway
    namespace: istio-ingress
    sectionName: https
  hostnames:
  - zigbee2mqtt.home.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: zigbee2mqtt
      port: 8080
