prometheus_username: ENC[AES256_GCM,data:/C7zwUjf,iv:I+3VWSBd21gajxI1w56bF1Vz9+28my0hlxApWPXjKJc=,tag:+t6Ed9lBY26njY690I4eJQ==,type:str]
prometheus_password: ENC[AES256_GCM,data:MhCM3Kwd9B5Q3oqiHxcFPF4gtCriHg==,iv:4XsNo2RrBzXjnzV2s8sG09v9GxKF0LmDNO/bKuSgzvo=,tag:4F0vZxXVQHef+lmPr1bEZw==,type:str]
mqtt_user: ENC[AES256_GCM,data:h8rSTw==,iv:uiN5sf/1gQPrQbVeDWiN/5gUkUPvPanz7LRYoF5aBAU=,tag:c7f8i8cvCugTcHNpHii9uw==,type:str]
mqtt_pass: ENC[AES256_GCM,data:I4jzloeX/71hbrGt4NZw7fMJ0yNt271SpmJYZBVfhZdA4A==,iv:CN6S77bLvXUfL+txxEqlzJYbmQ4LSKvKuhYLHSZGFwY=,tag:8ZHdpdvwQwRENXxQli/++w==,type:str]
sops:
    age:
        - recipient: age1y5rqvlhmmfjs5xugxte9j4djl9ztk9v3w6n7sjg32pst5gw4vq5sey3mhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZTBHdnovM3J2VCtKMm92
            cFpLT2lRdVpVckZMYnNhY05aSHg3dllhNjI0CmwycWhyRjVua3l5RjBrdnhZY0lX
            cmo3Zm95THRmRTUyZWJ0dVNtQWVnL0kKLS0tIERXVkVSQVppTjlZVUNxTEJCdVFC
            bENqOEFIYkhMZ3VQdXJzKzNSYjhKaUEKskzjF3tt/atU8UnDnCekQRnAIBUrnRA2
            HAcNUDMm0WsM+w1nArKDkjISc46igJLNxM3MdQdTdkcQM16EyTv3fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-03T12:12:35Z"
    mac: ENC[AES256_GCM,data:Ta9cK39Per9CFraAT7vN7+Mp+xUpjMhpNFmo2c4zyic2CbtAH1+jHmZLEKxWMsLDcxAlXIVcfjLouWOlFjLsx6sZFgt04lO/1knD/wlCqS1iKuRfklLGFKklOuM/zQiRrxeEkd5avV5DM8A6E2LYbWE1UIsdp+l63z4hljbdv/w=,iv:FvSqYvQwz9CMQHoG7GcJhVnPKlpIbj0r0q9rlHxh4WM=,tag:iP1qOdybYQtpG4D/n7RqMw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
