apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true

resources:
- namespace.yaml
- control-plane.yaml

helmCharts:
- name: k8s-monitoring
  releaseName: grafana-k8s-monitoring
  repo: https://grafana.github.io/helm-charts
  valuesFile: values.yaml
  version: 1.4.0


generators:
- |
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: secrets
    annotations:
      config.kubernetes.io/function: |
          exec:
            path: ksops
  files:
    - ./grafana-cloud.enc.yaml
patches:
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: Secret
    metadata:
        name: grafana-agent-credentials
