apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true

resources:
- namespace.yaml
- control-plane.yaml

helmCharts:
- name: k8s-monitoring
  repo: https://grafana.github.io/helm-charts
  releaseName: grafana-k8s-monitoring
  version: 1.2.0
  valuesFile: values.yaml

patchesStrategicMerge:
- |-
  $patch: delete
  apiVersion: v1
  kind: Secret
  metadata:
      name: grafana-agent-credentials

generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: secrets
    files:
      - ./grafana-cloud.enc.yaml
