apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oauth2-proxy

resources:
- namespace.yaml
- legacy.yaml
- ups.yaml

helmCharts:
- name: oauth2-proxy
  repo: https://oauth2-proxy.github.io/manifests
  releaseName: oauth2-proxy
  version: 6.17.0
  valuesFile: values.yaml

generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: secrets
    files:
      - ./oauth2-proxy.enc.yaml
