---
services:
  mpp-solar:
    build:
      context: .
      pull: true
    pull_policy: missing
    privileged: true
    restart: unless-stopped
    volumes:
    - ./mpp-solar.conf:/etc/mpp-solar/mpp-solar.conf
    - /var/lib/node_exporter:/var/lib/node_exporter
    devices:
    - /dev/ttyUSB0:/dev/ttyUSB0
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ls /var/lib/node_exporter/mpp-solar-*.prom
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      autoheal-app: true

  autoheal:
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal-app
    image: willfarrell/autoheal:latest
    network_mode: none
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock

  stale-metrics-cleaner:
    image: python:3.14-slim
    command:
    - /bin/sh
    - /stale-metrics-cleaner.sh
    volumes:
    - ./stale-metrics-cleaner.sh:/stale-metrics-cleaner.sh
    - /var/lib/node_exporter:/var/lib/node_exporter
