---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app: homebridge
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
  podMetricsEndpoints:
  - port: metrics