apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true

resources:
- namespace.yaml

helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: kube-prometheus-stack
  version: 51.2.0
  valuesFile: values.yaml
- name: node-exporter-textfiles
  repo: https://galexrt.github.io/container-node_exporter-textfiles
  values:
    image:
      repository: ghcr.io/thisisqasim/node-exporter-textfiles
      image:
        tag: fork
    textfiles: [{"name": "smartmon", "script": "smartmon.sh", "outputFilename": "smartmon", "interval": 900, "additionalEnv": [], "additionalVolumeMounts": [{"mountPath": "/dev", "name": "host-dev", "readOnly": true}], "resources": {}}]


generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: secrets
    files:
      - ./remote-prometheus.enc.yaml
