apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true

resources:
- namespace.yaml
- ingress-nginx.yaml

helmCharts:
- name: kube-prometheus-stack
  namespace: monitoring
  releaseName: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  version: 68.3.0
  includeCRDs: true
  valuesFile: kube-prometheus-stack.yaml
- name: node-exporter-textfiles
  releaseName: node-exporter-textfiles  
  repo: https://galexrt.github.io/container-node_exporter-textfiles
  version: 0.1.3
  valuesFile: node-exporter-textfiles.yaml


patches:
- target:
    group: apps
    kind: DaemonSet
    name: node-exporter-textfiles
    version: v1
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: monitoring
- target:
    group:
    kind: ServiceAccount
    name: node-exporter-textfiles
    version: v1
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: monitoring


generators:
- |
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: secrets
    annotations:
      config.kubernetes.io/function: |
          exec:
            path: ksops
  files:
    - ./remote-prometheus.enc.yaml    
