apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: household
resources:
- namespace.yaml
- lubelogger.yaml
- actualbudget.yaml
- mealie.yaml

generators:
- |
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: secret-envs
    annotations:
      config.kubernetes.io/function: |
          exec:
            path: ksops
  secretFrom:
  - metadata:
      name: lubelogger
      annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    envs:
    - ./lubelogger.enc.env
  - metadata:
      name: mealie
      annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    envs:
    - ./mealie.enc.env
