---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      containers:
      - image: ghcr.io/jellyfin/jellyfin:10.10.2
        imagePullPolicy: IfNotPresent
        name: jellyfin
        env:
        - name: JELLYFIN_PublishedServerUrl
          value: "https://jellyfin.home.com"
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /cache
          name: cache
        - mountPath: /media
          name: media
        ports:
        - containerPort: 8096
        startupProbe:
          tcpSocket:
            port: 8096
          failureThreshold: 60
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8096
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 8096
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            cpu: "250m"
            memory: "2Gi"
            smarter-devices/dri_card0: 1
            smarter-devices/dri_renderD128: 1
          limits:
            memory: "4Gi"
            smarter-devices/dri_card0: 1
            smarter-devices/dri_renderD128: 1
      volumes:
        - name: config
          hostPath:
            path: /home/entertainment/jellyfin/config
            type: Directory
        - name: cache
          hostPath:
            path: /home/entertainment/jellyfin/cache
            type: Directory
        - name: media
          hostPath:
            path: /mnt/external/media
            type: Directory
      nodeSelector:
        kubernetes.io/hostname: node3
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  ports:
  - port: 8096
    protocol: TCP
    targetPort: 8096
  selector:
    app: jellyfin
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  labels:
    app: jellyfin
  annotations:
    kubernetes.io/ingress.class: "nginx"
    gethomepage.dev/description: Media Player
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Entertainment
    gethomepage.dev/icon: jellyfin.png
    gethomepage.dev/name: Jellyfin
    gethomepage.dev/pod-selector: app=jellyfin
    gethomepage.dev/weight: "0"
    gethomepage.dev/widget.type: jellyfin
    gethomepage.dev/widget.url: http://jellyfin.entertainment.svc:8096
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_JELLYFIN_KEY}}"
    gethomepage.dev/widget.enableBlocks: "true"
    gethomepage.dev/widget.enableNowPlaying: "true"
spec:
  tls:
  - hosts:
    - jellyfin.home.com
  rules:
  - host: jellyfin.home.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyfin
            port:
              number: 8096
