---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metube
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  # Create can not be restricted to a resource name.
  verbs: ["create"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["events"]
  verbs: ["get", "create", "patch"]
- apiGroups: [""] # "" indicates the core API group
  resourceNames: ["metube-tailscale-state"]
  resources: ["secrets"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metube
subjects:
- kind: ServiceAccount
  name: "metube"
roleRef:
  kind: Role
  name: metube
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metube
  labels:
    app: metube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metube
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: metube
    spec:
      serviceAccount: metube
      containers:
      - image: ghcr.io/tailscale/tailscale:v1.86.5
        imagePullPolicy: IfNotPresent
        name: tailscale
        env:
        - name: TS_HOSTNAME
          value: "metube"
        - name: TS_EXTRA_ARGS
          value: "--login-server https://headscale.home.com:443"
        - name: TS_KUBE_SECRET
          value: "metube-tailscale-state"
        - name: TS_DEBUG_FIREWALL_MODE
          value: "auto"
        - name: TS_USERSPACE
          value: "true"
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: metube
              key: TS_AUTHKEY
              optional: true
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "64Mi"
      - image: ghcr.io/alexta69/metube:2025.08.28
        imagePullPolicy: IfNotPresent
        name: metube
        env:
        - name: UID
          value: "1001"
        - name: GID
          value: "1001"
        - name: YTDL_OPTIONS
          value: '{"proxy": "socks5://100.64.0.5:1055/", "concurrent_fragment_downloads": 1, "sleep_interval_requests": 5, "throttledratelimit": 400000, "nopart": true, "verbose": true}'
        volumeMounts:
        - mountPath: /downloads
          name: downloads
        ports:
        - containerPort: 8081
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"
          limits:
            memory: "512Mi"
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
      volumes:
        - name: downloads
          hostPath:
            path: /mnt/external/Downloads/ytdl
            type: Directory
        - name: wireguard
          secret:
            secretName: wireguard
      nodeSelector:
        kubernetes.io/hostname: node3
---
apiVersion: v1
kind: Service
metadata:
  name: metube
  labels:
    app: metube
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: metube
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metube
  labels:
    app: metube
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: http://authentik-server.authentik.svc.cluster.local/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: https://authentik.home.com/outpost.goauthentik.io/start?rd=https://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-snippet: |
        proxy_set_header X-Forwarded-Host $http_host;
    nginx.ingress.kubernetes.io/auth-cache-key: $cookie_authentik_proxy_EhWySFtO
    nginx.ingress.kubernetes.io/auth-cache-duration: 200 202 10m, 401 5s
    gethomepage.dev/description: YouTube Downloader
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Entertainment
    gethomepage.dev/icon: metube.png
    gethomepage.dev/name: Metube
    gethomepage.dev/pod-selector: app=metube
    gethomepage.dev/weight: "40"
spec:
  tls:
  - hosts:
    - ytdl.home.com
  rules:
  - host: ytdl.home.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: metube
            port:
              number: 8081
