---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metube
  labels:
    app: metube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metube
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: metube
    spec:
      initContainers:
      - args:
        - -c
        - modprobe iptable_nat
        command:
        - /bin/sh
        image: public.ecr.aws/docker/library/busybox
        name: sysctl
        securityContext:
          privileged: true        
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
      containers:
      - image: masipcat/wireguard-go
        imagePullPolicy: Always
        name: wireguard
        volumeMounts:
        - mountPath: /etc/wireguard
          name: wireguard
          readOnly: true
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "64Mi"
        securityContext:
          privileged: true
      - image: ghcr.io/alexta69/metube:latest
        imagePullPolicy: Always
        name: metube
        env:
        - name: UID
          value: "1001"
        - name: GID
          value: "1001"
        - name: YTDL_OPTIONS
          value: '{"concurrent_fragment_downloads": 1, "sleep_interval_requests": 5, "throttledratelimit": 400000, "nopart": true, "verbose": true}'
        volumeMounts:
        - mountPath: /downloads
          name: downloads
        ports:
        - containerPort: 8081
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"
          limits:
            memory: "512Mi"
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
      volumes:
        - name: downloads
          hostPath:
            path: /mnt/external/Downloads/ytdl
            type: Directory
        - name: modules
          hostPath:
            path: /lib/modules
            type: Directory
        - name: wireguard
          secret:
            secretName: wireguard
      nodeSelector:
        disk-type: media
---
apiVersion: v1
kind: Service
metadata:
  name: metube
  labels:
    app: metube
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: metube
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metube
  labels:
    app: metube
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-signin: https://iap.home.com/oauth2/start?rd=https://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.utilities.svc.cluster.local/oauth2/auth
    nginx.ingress.kubernetes.io/auth-cache-key: $cookie__oauth2_proxy
    nginx.ingress.kubernetes.io/auth-cache-duration: 200 202 10m, 401 0m
    gethomepage.dev/description: YouTube Downloader
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Entertainment
    gethomepage.dev/icon: metube.png
    gethomepage.dev/name: Metube
    gethomepage.dev/weight: "40"
spec:
  tls:
  - hosts:
    - ytdl.home.com
  rules:
  - host: ytdl.home.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: metube
            port:
              number: 8081
