---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - image: lscr.io/linuxserver/sonarr:4.0.12
        imagePullPolicy: IfNotPresent
        name: sonarr
        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "Asia/Karachi"
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data
          name: data
        ports:
        - containerPort: 8989
        livenessProbe:
          tcpSocket:
            port: 8989
          initialDelaySeconds: 600
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 8989
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            cpu: "150m"
          limits:
            memory: "512Mi"
      volumes:
        - name: config
          hostPath:
            path: /home/entertainment/sonarr
            type: Directory
        - name: data
          hostPath:
            path: /mnt/external
            type: Directory
      nodeSelector:
        kubernetes.io/hostname: node3
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  ports:
  - port: 8989
    protocol: TCP
    targetPort: 8989
  selector:
    app: sonarr
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  labels:
    app: sonarr
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: http://authentik-server.authentik.svc.cluster.local/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: https://authentik.home.com/outpost.goauthentik.io/start?rd=https://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-snippet: |
        proxy_set_header X-Forwarded-Host $http_host;
    nginx.ingress.kubernetes.io/auth-cache-key: $cookie_authentik_proxy_EhWySFtO
    nginx.ingress.kubernetes.io/auth-cache-duration: 200 202 10m, 401 5s
    gethomepage.dev/description: TV Shows downloader
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Entertainment
    gethomepage.dev/icon: sonarr.png
    gethomepage.dev/name: Sonarr
    gethomepage.dev/pod-selector: app=sonarr
    gethomepage.dev/weight: "30"
    gethomepage.dev/widget.type: sonarr
    gethomepage.dev/widget.url: http://sonarr.entertainment.svc:8989
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_SONARR_KEY}}"
spec:
  tls:
  - hosts:
    - sonarr.home.com
  rules:
  - host: sonarr.home.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 8989
