apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sunshine
  name: sunshine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sunshine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sunshine
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "name" : "macvlan-conf", "namespace": "kube-system", "interface": "macvlan0", "ips": [ "y.y.y.y
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      containers:
      - image: lizardbyte/sunshine:v2025.930.130407-ubuntu-24.04
        name: sunshine
        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "Asia/Karachi"
        ports:
        - name: http
          containerPort: 47990
          protocol: TCP
        startupProbe:
          tcpSocket:
            port: http
          failureThreshold: 60
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            smarter-devices/dri_card0: 1
            smarter-devices/dri_renderD128: 1
          limits:
            smarter-devices/dri_card0: 1
            smarter-devices/dri_renderD128: 1
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /external
          name: external
      volumes:
        - name: config
          hostPath:
            path: /home/entertainment/sunshine/config
            type: Directory
        - name: external
          hostPath:
            path: /mnt/external
            type: Directory
      nodeSelector:
        kubernetes.io/hostname: node3
---
apiVersion: v1
kind: Service
metadata:
  name: sunshine
  labels:
    app: sunshine
spec:
  ports:
  - port: 47990
    protocol: TCP
    targetPort: http
  selector:
    app: sunshine
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sunshine
  labels:
    app: sunshine
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    gethomepage.dev/description: Game Streaming
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Entertainment
    gethomepage.dev/icon: sunshine.png
    gethomepage.dev/name: sunshine
    gethomepage.dev/pod-selector: app=sunshine
    # gethomepage.dev/weight: "0"
    # gethomepage.dev/widget.type: sunshine
    # gethomepage.dev/widget.url: http://sunshine.entertainment.svc:47990
    # gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_sunshine_KEY}}"
    # gethomepage.dev/widget.enableBlocks: "true"
    # gethomepage.dev/widget.enableNowPlaying: "true"
spec:
  tls:
  - hosts:
    - sunshine.home.com
  rules:
  - host: sunshine.home.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sunshine
            port:
              number: 47990
