# yum install -y https://repo.radeon.com/amdgpu-install/7.0.1/el/9.6/amdgpu-install-7.0.1.70001-1.el9.noarch.rpm
# yum clean all
# yum install "kernel-headers" "kernel-devel" "kernel-devel-matched"
# dnf install -y amdgpu-dkms
# sed -i 's/$amdgpudistro/9.6/g' /etc/yum.repos.d/amdgpu.repo /etc/yum.repos.d/amdgpu-proprietary.repo /etc/yum.repos.d/rocm.repo
# amdgpu-install -y --accept-eula --vulkan=radv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sunshine
  labels:
    app: sunshine
data:
  dri.conf: |
    Section "Device"
        Identifier  "AMD GPU"
        Driver      "amdgpu"
        Option      "DRI" "3"
        Option      "TearFree" "true"
        Option      "VirtualHeads" "1"    # For virtual display
        Option      "SWcursor" "true"     # For virtual mouse cursor
    EndSection 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sunshine
  name: sunshine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sunshine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sunshine
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "name" : "macvlan-conf", "namespace": "kube-system", "interface": "macvlan0", "ips": [ "y.y.y.y
    spec:
      enableServiceLinks: false
      securityContext:
        fsGroup: 1001
      containers:
      - image: ghcr.io/steam-headless/steam-headless:debian@sha256:453e03d7a7e948db9f9c78569f3936561472797159dcf415a8ba89a20b68ca72
        name: server
        securityContext:
          privileged: true
        command:
        - /bin/bash
        - -c
        - |
          ulimit -n 1048576
          sed -i 's/Device          "Configured Video Device"/Device          "AMD GPU"/g' /templates/xorg/xorg.dummy.conf
          apt-get update && apt-get install -y --no-install-recommends mesa-va-drivers
          exec /entrypoint.sh
        env:
        - name: DISPLAY
          value: :55
        - name: USER_LOCALES
          value: 'en_US.UTF-8 UTF-8'
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: UMASK
          value: '000'
        - name: TZ
          value: "Asia/Karachi"
        - name: SHM_SIZE
          value: '2G'
        - name: MODE
          value: 'primary'
        - name: WEB_UI_MODE
          value: 'vnc'
        - name: ENABLE_VNC_AUDIO
          value: 'false'
        - name: PORT_NOVNC_WEB
          value: '8083'
        - name: NEKO_NAT1TO1
          value: ''
        - name: ENABLE_SUNSHINE
          value: 'false'
        - name: ENABLE_EVDEV_INPUTS
          value: 'true'
        - name: STEAM_ARGS
          value: '-silent -eula=yes'
        - name: FORCE_X11_DUMMY_CONFIG
          value: 'true'
        - name: ENABLE_SID
          value: 'false'
        # - name: INSTALL_EXTRAS
        #   value: '1' # installs additional dependencies, including VC++ Redist
        envFrom:
        - secretRef:
            name: sunshine
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - file /tmp/.X11-unix/X55 | grep socket
          failureThreshold: 600
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - file /tmp/.X11-unix/X55 | grep socket
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            smarter-devices/kfd: 1
            smarter-devices/dri_card0: 1
            smarter-devices/dri_renderD128: 1
          limits:
            smarter-devices/kfd: 1
            smarter-devices/dri_card0: 1
            smarter-devices/dri_renderD128: 1
        volumeMounts:
        - mountPath: /home/default/Games/
          name: external
          subPath: games
        - mountPath: /mnt/games/
          name: external
          subPath: games 
        - mountPath: /mnt/external/
          name: external
        - mountPath: /home/default/
          name: home
          subPath: home
        - mountPath: /etc/X11/xorg.conf.d/09-dri.conf
          name: config
          subPath: dri.conf
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /tmp/.X11-unix/
          name: x11-socket
        - mountPath: /tmp/pulse/
          name: pulse-socket
      - name: sunshine
        image: lizardbyte/sunshine:v2025.930.130407-ubuntu-24.04
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        ports:
        - name: http
          containerPort: 47990
          protocol: TCP
        startupProbe:
          tcpSocket:
            port: http
          failureThreshold: 600
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
        - name: DISPLAY
          value: :55
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "Asia/Karachi"
        - name: PULSE_SERVER
          value: /tmp/pulse/pulse-socket
        - name: XDG_RUNTIME_DIR
          value: /tmp/.X11-unix
        envFrom:
        - secretRef:
            name: sunshine
        resources:
          requests:
            smarter-devices/dri_card0: 1
            smarter-devices/dri_renderD128: 1
          limits:
            smarter-devices/dri_card0: 1
            smarter-devices/dri_renderD128: 1
        volumeMounts:
        - mountPath: /config
          name: home
          subPath: config
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /tmp/.X11-unix/
          name: x11-socket
        - mountPath: /tmp/pulse/
          name: pulse-socket
      volumes:
      - name: home
        hostPath:
          path: /home/entertainment/sunshine/
          type: Directory
      - name: external
        hostPath:
          path: /mnt/external
          type: Directory
      - name: config
        configMap:
          name: sunshine
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi
      - name: x11-socket
        emptyDir: {}
      - name: pulse-socket
        emptyDir: {}
      nodeSelector:
        kubernetes.io/hostname: node3
---
apiVersion: v1
kind: Service
metadata:
  name: sunshine
  labels:
    app: sunshine
spec:
  ports:
  - port: 47990
    protocol: TCP
    targetPort: http
  selector:
    app: sunshine
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sunshine
  labels:
    app: sunshine
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    gethomepage.dev/description: Game Streaming
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Entertainment
    gethomepage.dev/icon: sunshine.png
    gethomepage.dev/name: sunshine
    gethomepage.dev/pod-selector: app=sunshine
spec:
  tls:
  - hosts:
    - sunshine.home.com
  rules:
  - host: sunshine.home.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sunshine
            port:
              number: 47990
