---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: transmission
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      containers:
      - image: ghcr.io/thisisqasim/transmission:0.0.1
        imagePullPolicy: IfNotPresent
        name: transmission
        env:
        - name: TRANSMISSION_DOWNLOAD_LIMIT
          value: "1024"
        - name: TRANSMISSION_DOWNLOAD_QUEUE
          value: "20"
        - name: TRANSMISSION_AUTH
          value: "false"
        volumeMounts:
        - mountPath: /downloads
          name: downloads
        - mountPath: /etc/transmission-daemon/torrents
          name: torrents
        - mountPath: /etc/transmission-daemon/resume
          name: resume
        ports:
        - containerPort: 9091
        livenessProbe:
          tcpSocket:
            port: 9091
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 9091
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            cpu: "250m"
          limits:
            memory: "1536Mi"
      volumes:
        - name: downloads
          hostPath:
            path: /mnt/external/Downloads
            type: Directory
        - name: torrents
          hostPath:
            path: /mnt/external/Torrents/torrent.
            type: Directory
        - name: resume
          hostPath:
            path: /mnt/external/Torrents/transmission
            type: Directory
      nodeSelector:
        disk-type: media
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: transmission
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission
  labels:
    app: transmission
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-signin: https://iap.home.com/oauth2/start?rd=https://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.utilities.svc.cluster.local/oauth2/auth
    nginx.ingress.kubernetes.io/auth-cache-key: $cookie__oauth2_proxy
    nginx.ingress.kubernetes.io/auth-cache-duration: 200 202 10m, 401 0m
    gethomepage.dev/description: Torrent downloader
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Entertainment
    gethomepage.dev/icon: transmission.png
    gethomepage.dev/name: Transmission
    gethomepage.dev/pod-selector: app=transmission
    gethomepage.dev/weight: "10"
    gethomepage.dev/widget.type: transmission
    gethomepage.dev/widget.url: http://transmission.entertainment.svc:9091
spec:
  tls:
  - hosts:
    - torrent.home.com
  rules:
  - host: torrent.home.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: transmission
            port:
              number: 9091
