apiVersion: v1
kind: ConfigMap
metadata:
  name: smarter-device-manager
  namespace: kube-system
data:
  conf.yaml: |
        - devicematch: ^snd$
          nummaxdevices: 20
        - devicematch: ^dri.*$
          nummaxdevices: 20
        - devicematch: ^rtc0$
          nummaxdevices: 20
