---
apiVersion: v1
kind: Namespace
metadata:
  name: authentik
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-pgsql
  namespace: authentik
spec:
  instances: 2
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 17
  bootstrap:
    recovery:
      source: source
  externalClusters:
  - name: source
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: minio-store
        serverName: authentik-pgsql-recovery
  postgresql:
    parameters:
      max_wal_size: 2GB
  storage:
    size: 1Gi
    storageClass: local-path
  backup:
    retentionPolicy: "7d"
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: minio-store
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio-store
  namespace: authentik
spec:
  retentionPolicy: "30d"
  configuration:
    destinationPath: s3://authentik-postgres-backup/
    endpointURL: https://s3.home.com
    s3Credentials:
      accessKeyId:
        name: authentik-pgsql-s3
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: authentik-pgsql-s3
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-pgsql
  namespace: authentik
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: authentik-pgsql
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
