---
apiVersion: v1
kind: Namespace
metadata:
  name: authentik
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
  namespace: authentik
data:
  init.sql: |
    \c authentik-db
    GRANT CREATE ON SCHEMA public TO "authentik-db";
---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: authentik-db
  namespace: authentik
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-16.3-1
  postgresVersion: 16
  databaseInitSQL:
    key: init.sql
    name: init-sql
  instances:
    - replicas: 2
      dataVolumeClaimSpec:
        storageClassName: local-path
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: authentik-db
                  postgres-operator.crunchydata.com/instance-set: "00"
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.51-1
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            storageClassName: local-path
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi