---
apiVersion: v1
kind: Namespace
metadata:
  name: authentik
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-pgsql
  namespace: authentik
spec:
  instances: 2
  bootstrap:
    initdb:
      database: authentik
  postgresql:
    parameters:
      "pgaudit.log": "all, -misc"
      "pgaudit.log_catalog": "off"
      "pgaudit.log_parameter": "on"
      "pgaudit.log_relation": "on"
  storage:
    size: 1Gi
    storageClass: local-path
  backup:
    barmanObjectStore:
      destinationPath: s3://authentik-postgres-backup/
      endpointURL: https://s3.home.com
      s3Credentials:
        accessKeyId:
          name: authentik-pgsql-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: authentik-pgsql-s3
          key: ACCESS_SECRET_KEY
    retentionPolicy: "30d"
