---
apiVersion: v1
kind: Namespace
metadata:
  name: authentik
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-pgsql
  namespace: authentik
spec:
  instances: 2
  bootstrap:
    initdb:
      database: authentik
  postgresql:
    parameters:
      "pgaudit.log": "all, -misc"
      "pgaudit.log_catalog": "off"
      "pgaudit.log_parameter": "on"
      "pgaudit.log_relation": "on"
  storage:
    size: 1Gi
    storageClass: local-path
  backup:
    barmanObjectStore:
      destinationPath: s3://authentik-postgres-backup/
      endpointURL: https://s3.home.com
      s3Credentials:
        accessKeyId:
          name: authentik-pgsql-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: authentik-pgsql-s3
          key: ACCESS_SECRET_KEY
    retentionPolicy: "30d"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
  namespace: authentik
data:
  init.sql: |
    \c authentik-db
    GRANT CREATE ON SCHEMA public TO "authentik-db";
---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: authentik-db
  namespace: authentik
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-16.3-1
  postgresVersion: 16
  databaseInitSQL:
    key: init.sql
    name: init-sql
  instances:
    - replicas: 2
      dataVolumeClaimSpec:
        storageClassName: local-path
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: authentik-db
                  postgres-operator.crunchydata.com/instance-set: "00"
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.51-1
      configuration:
      - secret:
          name: authentik-s3-creds
      global:
        repo2-s3-uri-style: path
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            storageClassName: local-path
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
      - name: repo2
        s3:
          bucket: "authentik-postgres-backup"
          endpoint: "s3.home.com"
          region: "eu-central-1"
