apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- external-dns.yaml
- smarter-device-manager.yaml
- github.com/rancher/local-path-provisioner/deploy?ref=v0.0.26

generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: secrets
    secretFrom:
    - metadata:
        name: pihole-password
        namespace: external-dns
      envs:
      - pihole-password.enc.env
