apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- external-dns.yaml
- smarter-device-manager.yaml
- github.com/rancher/local-path-provisioner/deploy?ref=v0.0.26
- github.com/CrunchyData/postgres-operator-examples/kustomize/install/namespace
- github.com/CrunchyData/postgres-operator-examples/kustomize/install/default

patches:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: ".*.postgres-operator.crunchydata.com"
  patch: |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: postgres-operator.crunchydata.com
      annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true

generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: secrets
    secretFrom:
    - metadata:
        name: pihole-password
        namespace: external-dns
      envs:
      - pihole-password.enc.env
