apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- smarter-device-manager.yaml
- github.com/rancher/local-path-provisioner/deploy?ref=v0.0.32&timeout=90s
- https://github.com/cloudnative-pg/cloudnative-pg/releases/download/v1.27.0/cnpg-1.27.0.yaml
- https://raw.githubusercontent.com/cloudnative-pg/postgres-containers/main/Debian/ClusterImageCatalog-bookworm.yaml
- https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.6.0/manifest.yaml
- authentikdb.yaml

helmCharts:
- name: authentik
  namespace: authentik
  releaseName: authentik
  repo: https://charts.goauthentik.io
  version: 2025.8.1
  valuesFile: authentik.yaml
- name: spegel
  namespace: spegel
  releaseName: spegel
  repo: oci://ghcr.io/spegel-org/helm-charts
  version: 0.4.0
  valuesInline:
    spegel:
      resolveLatestTag: false
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus

patches:
- target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: .*.postgresql.cnpg.io
    version: v1
  patch: |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: postgresql.cnpg.io
      annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true
- target:
    group: storage.k8s.io
    kind: StorageClass
    name: local-path
    version: v1
  patch: |-
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: local-path
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"

generators:
- |
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: secrets
    annotations:
      config.kubernetes.io/function: |
          exec:
            path: ksops
  secretFrom:
  - metadata:
      name: authentik-key
      namespace: authentik
    envs:
    - authentik.enc.env
  - metadata:
      name: authentik-pgsql-s3
      namespace: authentik
    envs:
    - authentik-pgsql-s3.enc.env
