apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- external-dns.yaml
- smarter-device-manager.yaml
- github.com/rancher/local-path-provisioner/deploy?ref=v0.0.29
- github.com/CrunchyData/postgres-operator-examples/kustomize/install/namespace
- github.com/CrunchyData/postgres-operator-examples/kustomize/install/default
- authentikdb.yaml

helmCharts:
- name: authentik
  namespace: authentik
  releaseName: authentik
  repo: https://charts.goauthentik.io
  valuesFile: authentik.yaml
  version: 2024.8.2

patches:
- target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: .*.postgres-operator.crunchydata.com
    version: v1
  patch: |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: postgres-operator.crunchydata.com
      annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true
- target:
    group: storage.k8s.io
    kind: StorageClass
    name: local-path
    version: v1
  patch: |-
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: local-path
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"

generators:
- |
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: secrets
    annotations:
      config.kubernetes.io/function: |
          exec:
            path: ksops
  secretFrom:
  - metadata:
      name: pihole-password
      namespace: external-dns
    envs:
    - pihole-password.enc.env
  - metadata:
      name: authentik-key
      namespace: authentik
    envs:
    - authentik.enc.env
  - metadata:
      name: authentik-s3-creds
      namespace: authentik
    files:
      - s3.conf=./authentik-s3.enc.conf
