---
cluster:
  name: home
# One of these days this https://github.com/grafana/k8s-monitoring-helm/pull/47
# would get merged and I can remove these hacks
externalServices:
  prometheus:
    host: "PLACEHOLDER"
    basicAuth:
      username: "PLACEHOLDER"
      password: "PLACEHOLDER"
  loki:
    host: "PLACEHOLDER"
    basicAuth:
      username: "PLACEHOLDER"
      password: "PLACEHOLDER"
  tempo:
    host: "PLACEHOLDER"
    basicAuth:
      username: "PLACEHOLDER"
      password: "PLACEHOLDER"
metrics:
  cost:
    enabled: false
opencost:
  enabled: false
traces:
  enabled: true
grafana-agent:
  agent:
    extraPorts:
      - name: otlp-traces
        port: 4317
        targetPort: 4317
        protocol: TCP
  controller:
    volumes:
      extra:
      - name: grafana-agent-credentials
        secret:
          secretName: grafana-agent-credentials-kustomize
grafana-agent-logs:
  controller:
    volumes:
      extra:
      - name: grafana-agent-credentials
        secret:
          secretName: grafana-agent-credentials-kustomize
